### PR TITLE
Fix broken bis.doc.gov link

### PR DESCRIPTION
**Pull request by phildenhoff**
The link in the readme as-is 404's; I did some searching and I think this is the right page.

Signed-off-by: Phil Denhoff <phil@denhoff.ca>

### CODE REVIEW

**Comment by t3chguy** [comment]
> The Olm repository now lives at https://gitlab.matrix.org/matrix-org/olm.

**Comment by phildenhoff** [comment]
Yup! But the explanation why it's on Gitlab contains a link to bis.doc.gov that 404's, so this PR just fixes the link. Feel free to just make the edit yourself if you'd like :)

**Comment by t3chguy** [comment]
Oh hah, I was definitely in auto-pilot

**Review by t3chguy — APPROVED** [review]

**Comment by t3chguy** [comment]
Thanks for even the DCO sign-off. Very much appreciated.

**Comment by ara4n** [comment]
thanks! (i swear BIS break their links every few months...)

**Pull request merged**
